package swallow.com.model_data.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import swallow.com.model_data.model.BannerData;
import swallow.com.model_data.model.User;

import swallow.com.model_data.db.BannerDataDao;
import swallow.com.model_data.db.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bannerDataDaoConfig;
    private final DaoConfig userDaoConfig;

    private final BannerDataDao bannerDataDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bannerDataDaoConfig = daoConfigMap.get(BannerDataDao.class).clone();
        bannerDataDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        bannerDataDao = new BannerDataDao(bannerDataDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(BannerData.class, bannerDataDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        bannerDataDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public BannerDataDao getBannerDataDao() {
        return bannerDataDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
